server:
  port: 4000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shopping_cart?currentSchema=dev
    username: application
    password: Ab123123
jpa:
  show-sql: false
  hibernate:
    ddl-auto: none
  database-platform: org.hibernate.dialect.PostgreSQLDialect

delivery:
  fixedCost: 2.99
  costPerDelivery: 3
  costPerProduct: 3